[package]
name = "courier-agent"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
tauri = { version = "2.9.1", features = ["devtools"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }
